runTime: 3
numStateDim: 4
numSpaceDim: 2
startThreshold: 0.0
goalThreshold: 0.1
goalBias: 0.1
selectionRadius: 0.5
pruningRadius: 0.1
start: [0.0, 0.0, 1, 0]
goal: [1.0, 0.0, 1, 0]
lowerBound: [-0.1, -0.2, -1.01, -1.01]
upperBound: [1.3, 0.2, 1.01, 1.01]
controlDurationBound: [1, 1]
propagationStepSize: 1
planner: "SST"
objective: "PathLengthObjWithCostToGo"
file: "path.txt"
obstacles:
  # -
  #   type: "Square"
  #   x: 0.0
  #   y: -0.75
  #   l: 0.3

dynamics:
  0:
    A: [[1, 0, 0.125, 0],
        [0, 1, 0, 0.125],
        [0, 0, 1, 0],
        [0, 0, 1, 0]]
    b: [0, 0, 0, 0]
  1:
    A: [[1, 0, 0.125, 0],
        [0, 1, 0, 0.125],
        [0, 0, 0.86602540378, -0.5],
        [0, 0, 0.86602540378, 0.5]]
    b: [0, 0, 0, 0]
  -1:
    A: [[1, 0, 0.125, 0],
        [0, 1, 0, 0.125],
        [0, 0, 0.86602540378, 0.5],
        [0, 0, 0.86602540378, -0.5]]
    b: [0, 0, 0, 0]
