runTime: 2
goalThreshold: 9
start: [-90, 90, 1.570795]
goal: [90, -90, 0]
xBound: [-100, 100]
yBound: [-100, 100]
controlDurationBound: [1, 1]
propagationStepSize: 1
planner: "SST"
objective: "PathLength"
file: "path.txt"
obstacles:
  -
    type: "Square"
    x: 0.0
    y: -80.0
    l: 40.0

dynamics:
  1:
    A: [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 0]]
    b: [10, 0, 0]
  2:
    A: [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 0]]
    b: [0, 10, 1.570795]
  3:
    A: [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 0]]
    b: [-10, 0, 3.14159]
  4:
    A: [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 0]]
    b: [0, -10, -1.570795]
