runTime: 10
numStateDim: 4                        # X = [x,y,v,\theta]
numSpaceDim: 2
start: [0.0, 1.0, 0.0, 0.0]           # This will be set by the verifier
goal:  [1.0, 0.0, 0.0, 0.0]           # This will be set by the verifier
goalLowerBound: [0.9, -0.1, -0.1]
goalUpperBound: [1.1,  0.1,  0.1]
goalWeight: [1, 1, 1]
lowerBound: [-0.5, -0.5, -0.1, -3.14]
upperBound: [ 2.0,  2.0,  3.0,  3.14]
controlLowerBound: [-0.1, -0.1]       # U = [a, omega]
controlUpperBound: [ 0.1,  0.1]       # U = [a, omega]
goalBias: 0.1
selectionRadius: 0.6
pruningRadius: 0.08
propagationStepSize: 0.1
controlDurationBound: [1, 10]
planner: "SST"
objective: "PathLengthObjWithCostToGo"
file: "path.txt"
